apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability-services
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

    # Auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: observability-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Observability Services'

    # Performance
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/limit-rps: "5000"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - observability.canepro.me
      secretName: observability-tls
  rules:
    - host: observability.canepro.me
      http:
        paths:
          # Metrics
          - path: /api/v1/write
            pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  number: 80
          # Logs
          - path: /loki/api/v1/push
            pathType: Prefix
            backend:
              service:
                name: loki-gateway
                port:
                  number: 80
          # Traces (Maps external 443 -> internal 4318)
          - path: /v1/traces
            pathType: Prefix
            backend:
              service:
                name: tempo
                port:
                  number: 4318
