apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      region: us-ashburn-1
      vault: ocid1.vault.oc1.iad.ejux7f47aaauo.abuwcljtw7dmwl5s52lfvbk2calbk3vbjrhiguggqx67o5d7bv4zcwaaeeza
      principalType: InstancePrincipal
