apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  # Keep this short so accidental Secret deletion is self-healing quickly.
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: grafana
    creationPolicy: Owner
    template:
      data:
        admin-user: admin
      mergePolicy: Merge
  data:
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-json
        property: admin_password
    - secretKey: secret_key
      remoteRef:
        key: grafana-admin-json
        property: secret_key
